version: '1.0'
services:

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehicles
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
